/**
 * Generate ESP32/ESP8266 Arduino code with embedded HTML/CSS/JS
 * For standalone web-based control interface
 */

import { sanitizeWidgetId, widgetEndpoint } from './standaloneShared.js';

/**
 * Sanitize a string so it is safe to use as a C identifier.
 * - Keeps only [A-Za-z0-9_]
 * - Prefixes with underscore if it starts with a digit
 */
function sanitizeCIdentifier(name) {
  const cleaned = String(name ?? '').replace(/[^a-zA-Z0-9_]/g, '_');
  return cleaned.replace(/^([0-9])/, '_$1') || '_id';
}

/**
 * Get unique handler name for a widget (for ESP32 code generation)
 */
function getWidgetHandlerName(ctrl) {
  const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
  const widgetId = sanitizeWidgetId(ctrl.id);
  return `handle${gpioName}_${widgetId}`;
}

/**
 * Get unique state variable name for a widget
 */
function getWidgetStateName(ctrl, suffix = 'state') {
  const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
  const widgetId = sanitizeWidgetId(ctrl.id);
  return `${gpioName}_${widgetId}_${suffix}`;
}

/**
 * Generate ESP32 code
 */
export function generateStandaloneESP32(controls, htmlContent, options = {}) {
  const {
    ssid = 'ESP_Control',
    password = '12345678',
    serverPort = 80,
    serverEndpoint = 'control',
    apLocalIp = '192.168.4.1',
    apGateway = '192.168.4.1',
    apSubnet = '255.255.255.0',
  } = options;

  const deviceName = ssid.replace(/[^a-zA-Z0-9]/g, '_');

  // Parse IP addresses for Arduino
  const localIpParts = apLocalIp.split('.').map(Number);
  const gatewayParts = apGateway.split('.').map(Number);
  const subnetParts = apSubnet.split('.').map(Number);

  // Pre-allocate LEDC channels for all PWM widgets
  _resetChannels();
  let channel = 0;
  controls.forEach((ctrl) => {
    const orientation = ctrl.type === 'joystick_full' ? 'both' : (ctrl.orientation || 'both');
    if (ctrl.type === 'joystick_full') {
      if (orientation === 'both' || orientation === 'horizontal') {
        ctrl._channelX = channel++;
      }
      if (orientation === 'both' || orientation === 'vertical') {
        ctrl._channelY = channel++;
      }
    } else if (ctrl.type === 'joystick_x') {
      ctrl._channelX = channel++;
    } else if (ctrl.type === 'joystick_y') {
      ctrl._channelY = channel++;
    } else if (ctrl.type === 'slider' || ctrl.type === 'knob' || ctrl.type === 'number_input') {
      ctrl._channel = channel++;
    }
  });

  const gpioConfig = generateGPIOConfig(controls);
  const vpMapping = generateVPPinMapping(controls);
  const routes = generateRoutes(controls);
  const setupCode = generateSetupCode(controls, channel);
  const loopCode = generateLoopCode(controls);

  return `// Auto-generated ESP32 Standalone Controller
// Generated by IoT Platform
// Date: ${new Date().toISOString()}

#include <WiFi.h>
#include <WebServer.h>

// ==================== IP CONFIG (AP Mode) ====================
IPAddress localIP(${localIpParts.join(', ')});
IPAddress gateway(${gatewayParts.join(', ')});
IPAddress subnet(${subnetParts.join(', ')});

// ==================== WIFI AP CONFIG ====================
const char* AP_SSID = "${ssid}";
const char* AP_PASSWORD = "${password}";

// ==================== WEB SERVER ====================
const char* SERVER_ENDPOINT = "${serverEndpoint}";
WebServer server(${serverPort});

// ==================== PHYSICAL GPIO PINS ====================
${gpioConfig}

// ==================== VIRTUAL PINS (Blynk) ====================
${vpMapping}

// ==================== CONTROL STATES ====================
${generateStateVariables(controls)}

// ==================== HTML CONTENT ====================
const char INDEX_HTML[] PROGMEM = R"rawliteral(
${htmlContent}
)rawliteral";

// ==================== CORS HEADERS ====================
// CORS enabled for both browser-based control panel AND external mobile apps.
// Flutter app (Android/iOS) can connect via:
//   - AP mode: http://192.168.4.1:80/<widget_type>/<widget_id>?value=...
//   - STA mode: http://<esp-hostname>.local:80/<widget_type>/<widget_id>?value=...
// Query params expected per widget type:
//   - button/toggle/checkbox/icon_button: ?state=<onValue|offValue>
//   - slider/knob/number_input/stepper: ?value=<int>
//   - joystick_full: ?x=<int>&y=<int>
//   - joystick_x/y: ?value=<int>
//   - color_picker: ?r=<int>&g=<int>&b=<int>
//   - dpad/touch_pad: ?dir=<UP|DOWN|LEFT|RIGHT> or ?x=<int>&y=<int>
void sendCORS() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.sendHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  server.sendHeader("Access-Control-Allow-Headers", "Content-Type");
}

// ==================== HANDLE ROOT ====================
void handleRoot() {
  server.send_P(200, "text/html", INDEX_HTML);
}

// ==================== HANDLE OPTIONS ====================
void handleOptions() {
  sendCORS();
  server.send(204);
}

// ==================== ROUTES ====================
${routes}

// ==================== NOT FOUND ====================
void handleNotFound() {
  server.send(404, "text/plain", "Not Found");
}

// ==================== SETUP ====================
void setup() {
  Serial.begin(115200);
  delay(1000);

  Serial.println();
  Serial.println("=================================");
  Serial.println("ESP32 Standalone Controller");
  Serial.print("AP SSID: ");
  Serial.println(AP_SSID);
  Serial.print("AP Password: ");
  Serial.println(AP_PASSWORD);
  Serial.println("=================================");

${setupCode}

  // Configure AP
  if (!WiFi.softAPConfig(localIP, gateway, subnet)) {
    Serial.println("AP Config Failed!");
  }

  // Start AP
  if (WiFi.softAP(AP_SSID, AP_PASSWORD)) {
    Serial.println("AP Started Successfully!");
    Serial.print("AP IP: ");
    Serial.println(WiFi.softAPIP());
  } else {
    Serial.println("AP Start Failed!");
  }

  // Configure routes
  server.on("/", HTTP_GET, handleRoot);
  server.on("/", HTTP_OPTIONS, handleOptions);
  server.on("/"+String(SERVER_ENDPOINT), HTTP_GET, handleRoot);
  server.on("/"+String(SERVER_ENDPOINT), HTTP_OPTIONS, handleOptions);

${generateRouteRegistrations(controls)}

  server.onNotFound(handleNotFound);

  server.begin();
  Serial.println("Web Server Started on port 80");
}

// ==================== LOOP ====================
void loop() {
  server.handleClient();
${loopCode}
}
`;

  return code;
}

// Default GPIO values by widget type - used for code generation
const DEFAULT_GPIO = {
  joystick_full: [13, 15],    // X, Y
  joystick_x: [13],            // X only
  joystick_y: [15],            // Y only
  color_picker: [25, 26, 27],  // R, G, B
  button: [5],
  toggle: [5],
  checkbox: [5],
  icon_button: [5],
  touch_pad: [5],
  slider: [4],
  knob: [4],
  number_input: [4],
  dpad: [16, 17, 18, 19],     // UP, DOWN, LEFT, RIGHT
  stepper: [21, 22],           // IN1, IN2
};

// LEDC channel tracking for ESP32
const _channelMap = new Map();
function _getNextChannel() {
  const next = _channelMap.size;
  _channelMap.set(`_ch_${next}`, next);
  return next;
}
function _resetChannels() {
  _channelMap.clear();
}
function _assignChannels(ctrl, channels) {
  ctrl._channelX = channels.x;
  ctrl._channelY = channels.y;
}
function _getChannelsForCtrl(ctrl) {
  return {
    x: ctrl._channelX ?? 0,
    y: ctrl._channelY ?? 1
  };
}

function generateGPIOConfig(controls) {
  let config = '// ==================== PHYSICAL GPIO PINS ====================\n';
  config += '// REAL hardware pins for direct device control\n';
  config += '// Pin Mode: OUTPUT = relay/LED, INPUT = button/sensor\n';
  config += '// Generated with unique names per widget instance\n\n';

  // Generate per-widget GPIO definitions with unique names
  controls.forEach((ctrl) => {
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const uniqueName = `${gpioName}_${widgetId}`;
    const label = ctrl.label || ctrl.type;

    // Get GPIO array - use ctrl.gpio or fallback to defaults
    let gpioArray = ctrl.gpio;
    if (!gpioArray || gpioArray.length === 0) {
      const defaults = DEFAULT_GPIO[ctrl.type];
      if (defaults) {
        gpioArray = [...defaults];
      }
    }
    if (!gpioArray || gpioArray.length === 0) return;

    const mode = ctrl.gpioMode || 'output';
    const isVirtual = ctrl.pinType === 'virtual';

    // Single pin widgets (button, toggle, slider, etc.)
    if (gpioArray.length === 1) {
      const pin = gpioArray[0];
      const pinComment = isVirtual ? 'Virtual Pin' : mode.toUpperCase();
      config += `#define ${uniqueName}  ${pin}  // ${label} (id=${ctrl.id}) [${pinComment}]\n`;
    }
    // Multi-pin widgets (joystick, color_picker, dpad, stepper)
    else {
      const pinLabels = getMultiPinLabels(ctrl.type);
      gpioArray.forEach((pin, idx) => {
        const pinLabel = pinLabels[idx] || `PIN${idx + 1}`;
        const pinComment = isVirtual ? 'Virtual Pin' : '';
        config += `#define ${uniqueName}_${pinLabel.toUpperCase()}  ${pin}  // ${label} ${pinComment ? `- ${pinComment}` : ''} ${pinLabel} (id=${ctrl.id})\n`;
      });
    }
  });

  return config || '// No physical GPIO pins configured\n';
}

// Get pin labels for multi-pin widgets
function getMultiPinLabels(type) {
  const labels = {
    joystick_full: ['X', 'Y'],
    joystick_x: ['X'],
    joystick_y: ['Y'],
    color_picker: ['R', 'G', 'B'],
    dpad: ['UP', 'DOWN', 'LEFT', 'RIGHT'],
    stepper: ['IN1', 'IN2'],
  };
  return labels[type] || [];
}

// Generate Virtual Pin Mapping structure
function generateVPPinMapping(controls) {
  let mapping = '// ==================== VIRTUAL PINS ====================\n';
  mapping += '// Virtual pins for Blynk/IoT app integration\n';
  mapping += '// Requires manual physical pin mapping in getPhysicalPin()\n\n';

  // Collect all virtual pins with unique names
  const virtualPins = [];
  controls.forEach((ctrl) => {
    if (ctrl.pinType !== 'virtual') return;

    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const uniqueName = `${gpioName}_${widgetId}`;
    const label = ctrl.label || ctrl.type;
    const mode = ctrl.gpioMode || 'output';
    const modeNum = mode === 'input' ? 1 : mode === 'pwm' ? 2 : 0;

    virtualPins.push({
      vp: ctrl.virtualPin ?? 0,
      name: uniqueName,
      label: label,
      modeNum: modeNum,
      mode: mode,
      ctrl: ctrl,
    });
  });

  // Expand joystick_full into separate X and Y virtual pins
  const expandedVPs = [];
  virtualPins.forEach((vp) => {
    const orientation = vp.ctrl.type === 'joystick_full' ? 'both' : (vp.ctrl.orientation || 'both');
    if (vp.name.includes('JOYSTICK_FULL') || vp.name.startsWith('JOYSTICK_FULL')) {
      if (orientation === 'both' || orientation === 'horizontal') {
        expandedVPs.push({
          vp: vp.vp,
          name: `${vp.name}_X`,
          label: `${vp.label} X`,
          modeNum: vp.modeNum,
          mode: vp.mode,
          ctrl: vp.ctrl,
        });
      }
      if (orientation === 'both' || orientation === 'vertical') {
        expandedVPs.push({
          vp: vp.vp + 1,
          name: `${vp.name}_Y`,
          label: `${vp.label} Y`,
          modeNum: vp.modeNum,
          mode: vp.mode,
          ctrl: vp.ctrl,
        });
      }
    } else {
      expandedVPs.push(vp);
    }
  });

  if (expandedVPs.length === 0) {
    return mapping + '// No virtual pins configured\n';
  }

  // Sort by VP number
  expandedVPs.sort((a, b) => a.vp - b.vp);

  // Generate VP_COUNT - count all entries including joystick X and Y
  mapping += `#define VP_COUNT ${expandedVPs.length}\n\n`;

  // Generate VP_MAP array
  mapping += 'struct VPPin {\n';
  mapping += '  uint8_t virtualPin;\n';
  mapping += '  const char* name;\n';
  mapping += '  uint8_t mode;  // 0=output, 1=input, 2=pwm\n';
  mapping += '};\n\n';

  mapping += 'const VPPin VP_MAP[VP_COUNT] = {\n';
  expandedVPs.forEach((vp, idx) => {
    const comma = idx < expandedVPs.length - 1 ? ',' : '';
    mapping += `  { ${vp.vp}, "${vp.name}", ${vp.modeNum} }  // ${vp.label} (id=${vp.ctrl.id})${comma}\n`;
  });
  mapping += '};\n\n';

  // Generate helper function to get physical pin from VP
  mapping += '// Helper: Get physical pin index for a virtual pin (user must customize)\n';
  mapping += 'uint8_t getPhysicalPin(uint8_t vp) {\n';
  mapping += '  // TODO: User should customize this function based on their hardware\n';
  mapping += '  // Example mapping:\n';
  mapping += '  // switch(vp) {\n';
  expandedVPs.forEach(vp => {
    mapping += `  //   case ${vp.vp}: return 13;  // ${vp.label}\n`;
  });
  mapping += '  //   default: return 0xFF;\n';
  mapping += '  // }\n';
  mapping += '  return 0xFF;  // Not mapped\n';
  mapping += '}\n\n';

  // Generate physical pin defines based on VP mapping
  mapping += '// Physical Pin Definitions (from VP mapping)\n';
  mapping += '// User should update these based on actual hardware\n';
  expandedVPs.forEach((vp) => {
    const modeComment = vp.mode === 'input' ? 'INPUT' : vp.mode === 'pwm' ? 'PWM' : 'OUTPUT';
    mapping += `// #define PIN_${vp.name}  <SET_PHYSICAL_PIN>  // VP${vp.vp} ${vp.label} (${modeComment})\n`;
  });

  return mapping;
}

// Helper to get pin label based on widget type
function getPinLabel(type, index) {
  const labels = {
    joystick_full: ['X', 'Y'],
    joystick_x: ['X'],
    joystick_y: ['Y'],
    color_picker: ['R', 'G', 'B'],
    dpad: ['UP', 'DOWN', 'LEFT', 'RIGHT'],
    stepper: ['IN1', 'IN2'],
  };
  return labels[type]?.[index] || `PIN${index + 1}`;
}

function generateStateVariables(controls) {
  let states = '// ==================== CONTROL STATES ====================\n';
  states += '// Per-widget state variables based on configuration\n\n';

  // Generate per-widget state variables with unique names
  controls.forEach((ctrl) => {
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const stateName = `${gpioName}_${widgetId}`;
    const label = ctrl.label || ctrl.type;

    if (['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(ctrl.type)) {
      const onVal = ctrl.onValue ?? 1;
      const offVal = ctrl.offValue ?? 0;
      states += `bool ${stateName}_state = false;  // ${label} (id=${ctrl.id}, ON=${onVal}, OFF=${offVal})\n`;
    }

    if (['slider', 'knob', 'number_input'].includes(ctrl.type)) {
      const min = ctrl.min ?? 0;
      const max = ctrl.max ?? 255;
      const init = Math.floor((min + max) / 2);
      states += `int ${stateName}_value = ${init};  // ${label} (id=${ctrl.id}, ${min}-${max})\n`;
    }

    if (ctrl.type === 'joystick_full') {
      states += `int ${stateName}_x = 128;  // ${label} X axis (id=${ctrl.id})\n`;
      states += `int ${stateName}_y = 128;  // ${label} Y axis (id=${ctrl.id})\n`;
    }

    if (ctrl.type === 'joystick_x') {
      states += `int ${stateName}_value = 128;  // ${label} X axis (id=${ctrl.id})\n`;
    }

    if (ctrl.type === 'joystick_y') {
      states += `int ${stateName}_value = 128;  // ${label} Y axis (id=${ctrl.id})\n`;
    }

    if (ctrl.type === 'color_picker') {
      states += `int ${stateName}_r = 0;  // ${label} Red (id=${ctrl.id})\n`;
      states += `int ${stateName}_g = 0;  // ${label} Green (id=${ctrl.id})\n`;
      states += `int ${stateName}_b = 0;  // ${label} Blue (id=${ctrl.id})\n`;
    }

    if (ctrl.type === 'stepper') {
      const min = ctrl.min ?? 0;
      states += `int ${stateName}_pos = ${min};  // ${label} position (id=${ctrl.id})\n`;
    }
  });

  return states || '// No states needed\n';
}

function generateRoutes(controls) {
  let routes = '';

  // Pre-allocate LEDC channels for joystick widgets
  _resetChannels();
  let channel = 0;
  controls.forEach((ctrl) => {
    const orientation = ctrl.type === 'joystick_full' ? 'both' : (ctrl.orientation || 'both');
    if (ctrl.type === 'joystick_full') {
      if (orientation === 'both' || orientation === 'horizontal') {
        ctrl._channelX = channel++;
      }
      if (orientation === 'both' || orientation === 'vertical') {
        ctrl._channelY = channel++;
      }
    } else if (ctrl.type === 'joystick_x') {
      ctrl._channelX = channel++;
    } else if (ctrl.type === 'joystick_y') {
      ctrl._channelY = channel++;
    }
  });

  // Generate per-widget route handlers with unique names
  controls.forEach((ctrl) => {
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const uniqueName = `${gpioName}_${widgetId}`;
    const handlerName = `handle${uniqueName}`;
    const pinName = `PIN_${uniqueName}`;
    const pin = ctrl.gpio?.[0] ?? 0;
    const mode = ctrl.gpioMode || 'output';
    const label = ctrl.label || ctrl.type;
    const min = ctrl.min ?? 0;
    const max = ctrl.max ?? 255;
    const invert = ctrl.invert ?? false;
    const onVal = ctrl.onValue ?? 1;
    const offVal = ctrl.offValue ?? 0;
    const isVirtual = ctrl.pinType === 'virtual';
    const virtualPin = ctrl.virtualPin ?? 0;

    // State variable names
    const stateVar = `${uniqueName}_state`;
    const valueVar = `${uniqueName}_value`;
    const xVar = `${uniqueName}_x`;
    const yVar = `${uniqueName}_y`;
    const rVar = `${uniqueName}_r`;
    const gVar = `${uniqueName}_g`;
    const bVar = `${uniqueName}_b`;
    const posVar = `${uniqueName}_pos`;

    // Get physical pin reference (for physical) or VP (for virtual)
    const getPhysicalPinRef = () => isVirtual ? `getPhysicalPin(${virtualPin})` : pinName;

    if (['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(ctrl.type)) {
      // Output mode: control relay/LED
      if (mode === 'output' || mode === 'pwm') {
        routes += `// ==================== HANDLE ${ctrl.type.toUpperCase()} ====================\n`;
        routes += `// Widget: ${label} (id=${ctrl.id})\n`;
        routes += `void ${handlerName}() {\n`;
        routes += `  sendCORS();\n`;
        if (isVirtual) {
          routes += `  uint8_t physPin = getPhysicalPin(${virtualPin});\n`;
          routes += `  if (physPin == 0xFF) {\n`;
          routes += `    server.send(400, "text/plain", "VP not mapped");\n`;
          routes += `    return;\n`;
          routes += `  }\n`;
          routes += `  if (server.hasArg("state")) {\n`;
          routes += `    int state = server.arg("state").toInt();\n`;
          if (invert) {
            routes += `    ${stateVar} = (state == ${onVal});\n`;
            routes += `    digitalWrite(physPin, ${stateVar} ? LOW : HIGH);\n`;
          } else {
            routes += `    ${stateVar} = (state == ${onVal});\n`;
            routes += `    digitalWrite(physPin, ${stateVar} ? HIGH : LOW);\n`;
          }
          routes += `    Serial.printf("${label} (VP${virtualPin}): %s\\n", ${stateVar} ? "ON" : "OFF");\n`;
          routes += `  }\n`;
        } else {
          routes += `  if (!server.hasArg("state")) {\n`;
          routes += `    server.send(400, "text/plain", "Missing state arg");\n`;
          routes += `    return;\n`;
          routes += `  }\n`;
          routes += `  if (server.arg("state").length() == 0) {\n`;
          routes += `    server.send(400, "text/plain", "Empty state arg");\n`;
          routes += `    return;\n`;
          routes += `  }\n`;
          routes += `  int stateVal = server.arg("state").toInt();\n`;
          if (invert) {
            routes += `  ${stateVar} = (stateVal == ${onVal});\n`;
            routes += `  digitalWrite(${pinName}, ${stateVar} ? LOW : HIGH);\n`;
          } else {
            routes += `  ${stateVar} = (stateVal == ${onVal});\n`;
            routes += `  digitalWrite(${pinName}, ${stateVar} ? HIGH : LOW);\n`;
          }
          routes += `  Serial.print("${label}: ");\n`;
          routes += `  Serial.println(${stateVar} ? "ON" : "OFF");\n`;
        }
        routes += `  server.send(200, "text/plain", ${stateVar} ? "ON" : "OFF");\n`;
        routes += `}\n\n`;
      }
      // Input mode: read button state
      else if (mode === 'input') {
        routes += `// ==================== HANDLE ${ctrl.type.toUpperCase()} ====================\n`;
        routes += `// Widget: ${label} (id=${ctrl.id}) - Input mode\n`;
        routes += `void ${handlerName}() {\n`;
        routes += `  sendCORS();\n`;
        if (isVirtual) {
          routes += `  uint8_t physPin = getPhysicalPin(${virtualPin});\n`;
          routes += `  if (physPin == 0xFF) {\n`;
          routes += `    server.send(400, "text/plain", "VP not mapped");\n`;
          routes += `    return;\n`;
          routes += `  }\n`;
          routes += `  int state = digitalRead(physPin);\n`;
          routes += `  Serial.printf("${label} (VP${virtualPin}) state: %d\\n", state);\n`;
        } else {
          routes += `  int state = digitalRead(${pinName});\n`;
          routes += `  Serial.printf("${label} state: %d\\n", state);\n`;
        }
        routes += `  server.send(200, "text/plain", String(state));\n`;
        routes += `}\n\n`;
      }
    }

    if (ctrl.type === 'slider') {
      routes += `// ==================== HANDLE SLIDER ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("value")) {\n`;
      routes += `    server.send(400, "text/plain", "Missing value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  if (server.arg("value").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Empty value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      if (invert) {
        routes += `  ${valueVar} = map(server.arg("value").toInt(), ${min}, ${max}, ${max}, ${min});\n`;
        routes += `  ${valueVar} = constrain(${valueVar}, ${min}, ${max});\n`;
      } else {
        routes += `  ${valueVar} = server.arg("value").toInt();\n`;
        routes += `  ${valueVar} = constrain(${valueVar}, ${min}, ${max});\n`;
      }
      if (isVirtual) {
        routes += `  uint8_t physPin = getPhysicalPin(${virtualPin});\n`;
        routes += `  if (physPin != 0xFF) ledcWrite(physPin, ${valueVar});\n`;
        routes += `  Serial.printf("${label} (VP${virtualPin}): %d\\n", ${valueVar});\n`;
      } else {
        const channels = _getChannelsForCtrl(ctrl);
        routes += `  ledcWrite(${channels.x}, ${valueVar});\n`;
        routes += `  Serial.printf("${label}: %d\\n", ${valueVar});\n`;
      }
      routes += `  server.send(200, "text/plain", String(${valueVar}));\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'knob') {
      routes += `// ==================== HANDLE KNOB ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("value")) {\n`;
      routes += `    server.send(400, "text/plain", "Missing value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  if (server.arg("value").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Empty value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      if (invert) {
        routes += `  ${valueVar} = map(server.arg("value").toInt(), ${min}, ${max}, ${max}, ${min});\n`;
        routes += `  ${valueVar} = constrain(${valueVar}, ${min}, ${max});\n`;
      } else {
        routes += `  ${valueVar} = server.arg("value").toInt();\n`;
        routes += `  ${valueVar} = constrain(${valueVar}, ${min}, ${max});\n`;
      }
      if (isVirtual) {
        routes += `  uint8_t physPin = getPhysicalPin(${virtualPin});\n`;
        routes += `  if (physPin != 0xFF) ledcWrite(physPin, ${valueVar});\n`;
        routes += `  Serial.printf("${label} (VP${virtualPin}): %d\\n", ${valueVar});\n`;
      } else {
        const channels = _getChannelsForCtrl(ctrl);
        routes += `  ledcWrite(${channels.x}, ${valueVar});\n`;
        routes += `  Serial.printf("${label}: %d\\n", ${valueVar});\n`;
      }
      routes += `  server.send(200, "text/plain", String(${valueVar}));\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'number_input') {
      routes += `// ==================== HANDLE NUMBER INPUT ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      if (isVirtual) {
        routes += `  uint8_t physPin = getPhysicalPin(${virtualPin});\n`;
        routes += `  if (physPin == 0xFF) {\n`;
        routes += `    server.send(400, "text/plain", "VP not mapped");\n`;
        routes += `    return;\n`;
        routes += `  }\n`;
      }
      routes += `  if (server.arg("method") == "POST") {\n`;
      routes += `    String body = server.arg("plain");\n`;
      routes += `    int idx = body.indexOf("\\"value\\":");\n`;
      routes += `    if (idx != -1) {\n`;
      routes += `      int start = idx + 8;\n`;
      routes += `      int end = body.indexOf("}", start);\n`;
      routes += `      String v = body.substring(start, end);\n`;
      routes += `      ${valueVar} = constrain(v.toInt(), ${min}, ${max});\n`;
      if (isVirtual) {
        routes += `      ledcWrite(physPin, ${valueVar});\n`;
      } else {
        const channels = _getChannelsForCtrl(ctrl);
        routes += `      ledcWrite(${channels.x}, ${valueVar});\n`;
      }
      routes += `    }\n`;
      routes += `  } else if (server.hasArg("value") && server.arg("value").length() > 0) {\n`;
      routes += `    ${valueVar} = constrain(server.arg("value").toInt(), ${min}, ${max});\n`;
      if (isVirtual) {
        routes += `    ledcWrite(physPin, ${valueVar});\n`;
      } else {
        const channels = _getChannelsForCtrl(ctrl);
        routes += `    ledcWrite(${channels.x}, ${valueVar});\n`;
      }
      routes += `  }\n`;
      routes += `  Serial.printf("${label}: %d\\n", ${valueVar});\n`;
      routes += `  server.send(200, "text/plain", String(${valueVar}));\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'joystick_full') {
      const orientation = ctrl.orientation || 'both';
      const deadzone = ctrl.deadzone ?? 10;
      const channels = _getChannelsForCtrl(ctrl);
      const vpChannelX = ctrl._vpChannelX ?? channels.x;
      const vpChannelY = ctrl._vpChannelY ?? channels.y;

      routes += `// ==================== HANDLE JOYSTICK ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id}) [${orientation}]\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;

      if (orientation === 'both' || orientation === 'horizontal') {
        routes += `  if (server.hasArg("x") && server.arg("x").length() > 0) {\n`;
        routes += `    ${xVar} = server.arg("x").toInt();\n`;
        routes += `    ${xVar} = constrain(${xVar}, ${min}, ${max});\n`;
        routes += `    ledcWrite(${vpChannelX}, ${xVar});\n`;
        routes += `    Serial.printf("${label} X: %d\\n", ${xVar});\n`;
        routes += `  }\n`;
      }

      if (orientation === 'both' || orientation === 'vertical') {
        routes += `  if (server.hasArg("y") && server.arg("y").length() > 0) {\n`;
        routes += `    ${yVar} = server.arg("y").toInt();\n`;
        routes += `    // Apply deadzone to reduce jitter\n`;
        routes += `    if (abs(${yVar}) < ${deadzone}) ${yVar} = 0;\n`;
        routes += `    ${yVar} = constrain(${yVar}, ${min}, ${max});\n`;
        routes += `    ledcWrite(${vpChannelY}, ${yVar});\n`;
        routes += `    Serial.printf("${label} Y: %d\\n", ${yVar});\n`;
        routes += `  }\n`;
      }

      routes += `  server.send(200, "text/plain", "OK");\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'joystick_x') {
      const deadzone = ctrl.deadzone ?? 10;
      const sensitivity = ctrl.sensitivity ?? 1.0;
      const gpioArray = ctrl.gpio?.length > 0 ? ctrl.gpio : DEFAULT_GPIO.joystick_x;
      const pinX = gpioArray[0];
      // Get channel number
      const channels = _getChannelsForCtrl(ctrl);

      routes += `// ==================== HANDLE JOYSTICK X ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id}) X axis\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("value") || server.arg("value").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Missing value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  ${valueVar} = server.arg("value").toInt();\n`;
      routes += `  // Apply deadzone\n`;
      routes += `  if (abs(${valueVar}) < ${deadzone}) ${valueVar} = 0;\n`;
      routes += `  // Apply sensitivity\n`;
      routes += `  float scaled = ${valueVar} * ${sensitivity};\n`;
      routes += `  ${valueVar} = constrain((int)scaled, ${min}, ${max});\n`;
      routes += `  ledcWrite(${channels.x}, ${valueVar});\n`;
      routes += `  Serial.printf("${label} X: %d\\n", ${valueVar});\n`;
      routes += `  server.send(200, "text/plain", String(${valueVar}));\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'joystick_y') {
      const deadzone = ctrl.deadzone ?? 10;
      const sensitivity = ctrl.sensitivity ?? 1.0;
      const channels = _getChannelsForCtrl(ctrl);

      routes += `// ==================== HANDLE JOYSTICK Y ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id}) Y axis\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("value") || server.arg("value").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Missing value arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  ${valueVar} = server.arg("value").toInt();\n`;
      routes += `  // Apply deadzone\n`;
      routes += `  if (abs(${valueVar}) < ${deadzone}) ${valueVar} = 0;\n`;
      routes += `  // Apply sensitivity\n`;
      routes += `  float scaled = ${valueVar} * ${sensitivity};\n`;
      routes += `  ${valueVar} = constrain((int)scaled, ${min}, ${max});\n`;
      routes += `  ledcWrite(${channels.y}, ${valueVar});\n`;
      routes += `  Serial.printf("${label} Y: %d\\n", ${valueVar});\n`;
      routes += `  server.send(200, "text/plain", String(${valueVar}));\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'color_picker') {
      const channels = _getChannelsForCtrl(ctrl);

      routes += `// ==================== HANDLE COLOR PICKER ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (server.hasArg("r") && server.arg("r").length() > 0) ${rVar} = server.arg("r").toInt();\n`;
      routes += `  if (server.hasArg("g") && server.arg("g").length() > 0) ${gVar} = server.arg("g").toInt();\n`;
      routes += `  if (server.hasArg("b") && server.arg("b").length() > 0) ${bVar} = server.arg("b").toInt();\n`;
      routes += `  ${rVar} = constrain(${rVar}, 0, 255);\n`;
      routes += `  ${gVar} = constrain(${gVar}, 0, 255);\n`;
      routes += `  ${bVar} = constrain(${bVar}, 0, 255);\n`;
      routes += `  ledcWrite(${channels.x}, ${rVar});\n`;
      routes += `  ledcWrite(${channels.y}, ${gVar});\n`;
      routes += `  ledcWrite(${channels.x + 1}, ${bVar});\n`;
      routes += `  Serial.printf("${label} RGB: R=%d G=%d B=%d\\n", ${rVar}, ${gVar}, ${bVar});\n`;
      routes += `  server.send(200, "text/plain", "OK");\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'dpad') {
      routes += `// ==================== HANDLE D-PAD ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("dir") || server.arg("dir").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Missing dir arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  String dir = server.arg("dir");\n`;
      routes += `  dir.toUpperCase();\n`;
      routes += `  Serial.print("${label}: ");\n`;
      routes += `  Serial.println(dir);\n`;
      routes += `  // Reset all pins first\n`;
      routes += `  digitalWrite(${uniqueName}_UP, LOW);\n`;
      routes += `  digitalWrite(${uniqueName}_DOWN, LOW);\n`;
      routes += `  digitalWrite(${uniqueName}_LEFT, LOW);\n`;
      routes += `  digitalWrite(${uniqueName}_RIGHT, LOW);\n`;
      routes += `  if (dir == "UP") digitalWrite(${uniqueName}_UP, HIGH);\n`;
      routes += `  else if (dir == "DOWN") digitalWrite(${uniqueName}_DOWN, HIGH);\n`;
      routes += `  else if (dir == "LEFT") digitalWrite(${uniqueName}_LEFT, HIGH);\n`;
      routes += `  else if (dir == "RIGHT") digitalWrite(${uniqueName}_RIGHT, HIGH);\n`;
      routes += `  server.send(200, "text/plain", "OK");\n`;
      routes += `}\n\n`;
    }

    if (ctrl.type === 'stepper') {
      routes += `// ==================== HANDLE STEPPER ====================\n`;
      routes += `// Widget: ${label} (id=${ctrl.id})\n`;
      routes += `void ${handlerName}() {\n`;
      routes += `  sendCORS();\n`;
      routes += `  if (!server.hasArg("dir") || server.arg("dir").length() == 0) {\n`;
      routes += `    server.send(400, "text/plain", "Missing dir arg");\n`;
      routes += `    return;\n`;
      routes += `  }\n`;
      routes += `  String dir = server.arg("dir");\n`;
      routes += `  dir.toLowerCase();\n`;
      routes += `  Serial.print("${label}: ");\n`;
      routes += `  Serial.println(dir);\n`;
      routes += `  if (dir == "up") {\n`;
      routes += `    digitalWrite(${uniqueName}_IN1, HIGH);\n`;
      routes += `    digitalWrite(${uniqueName}_IN2, LOW);\n`;
      routes += `    delay(10);\n`;
      routes += `    digitalWrite(${uniqueName}_IN1, LOW);\n`;
      routes += `    digitalWrite(${uniqueName}_IN2, HIGH);\n`;
      routes += `    delay(10);\n`;
      routes += `    ${posVar}++;\n`;
      routes += `  } else if (dir == "down") {\n`;
      routes += `    digitalWrite(${uniqueName}_IN1, LOW);\n`;
      routes += `    digitalWrite(${uniqueName}_IN2, HIGH);\n`;
      routes += `    delay(10);\n`;
      routes += `    digitalWrite(${uniqueName}_IN1, HIGH);\n`;
      routes += `    digitalWrite(${uniqueName}_IN2, LOW);\n`;
      routes += `    delay(10);\n`;
      routes += `    ${posVar}--;\n`;
      routes += `  }\n`;
      routes += `  ${posVar} = constrain(${posVar}, ${min}, ${max});\n`;
      routes += `  Serial.printf("${label} Position: %d\\n", ${posVar});\n`;
      routes += `  server.send(200, "text/plain", String(${posVar}));\n`;
      routes += `}\n\n`;
    }
  });

  return routes || '// No custom routes\n';
}

function generateRouteRegistrations(controls) {
  let regs = '  // ==================== ROUTE REGISTRATIONS ====================\n';

  // Register per-widget routes - MUST match HTML generator's widgetEndpoint()
  controls.forEach((ctrl) => {
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const handlerName = `handle${gpioName}_${widgetId}`;
    const endpoint = widgetEndpoint(ctrl);
    regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});  // ${ctrl.label || ctrl.type} (id=${ctrl.id})\n`;
  });

  return regs || '  // No routes registered\n';
}

function generateSetupCode(controls, startChannel = 0) {
  let setup = '  // Configure GPIO pins based on widget configuration\n';
  let channel = startChannel;

  // Configure per-widget pins
  // Configure all widgets, virtual pins are mapped via getPhysicalPin()
  controls.forEach((ctrl) => {
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const uniqueName = `${gpioName}_${widgetId}`;
    const mode = ctrl.gpioMode || 'output';
    const isVirtual = ctrl.pinType === 'virtual';

    // Get GPIO with defaults
    let gpioArray = ctrl.gpio;
    if (!gpioArray || gpioArray.length === 0) {
      const defaults = DEFAULT_GPIO[ctrl.type];
      if (defaults) {
        gpioArray = [...defaults];
      }
    }
    const pin = gpioArray?.[0] ?? 0;

    // Skip virtual pins for direct pinMode (they'll be handled via getPhysicalPin)
    if (isVirtual) {
      // For virtual pins, still setup LEDC if needed
      if (['slider', 'knob', 'number_input', 'joystick_full', 'joystick_x', 'joystick_y', 'color_picker'].includes(ctrl.type)) {
        // LEDC setup will be handled in multi-pin section
      }
      return;
    }

    if (!gpioArray || gpioArray.length === 0) return;

    // Output mode pins
    if (mode === 'output') {
      setup += `  pinMode(${uniqueName}, OUTPUT);  // ${ctrl.label || ctrl.type} (id=${ctrl.id})\n`;
    }
    // Input mode pins
    else if (mode === 'input') {
      setup += `  pinMode(${uniqueName}, INPUT);  // ${ctrl.label || ctrl.type} (id=${ctrl.id}) Input\n`;
    }
    // PWM mode for slider/knob
    else if (mode === 'pwm' || ['slider', 'knob', 'number_input'].includes(ctrl.type)) {
      setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} PWM (id=${ctrl.id})\n`;
      setup += `  ledcAttachPin(${uniqueName}, ${channel});\n`;
      channel++;
    }
  });

  // Handle multi-pin widgets
  controls.forEach((ctrl) => {
    const isVirtual = ctrl.pinType === 'virtual';
    const widgetId = sanitizeWidgetId(ctrl.id);
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const uniqueName = `${gpioName}_${widgetId}`;
    const orientation = ctrl.type === 'joystick_full' ? 'both' : (ctrl.orientation || 'both');

    // Get GPIO array with defaults
    let gpioArray = ctrl.gpio;
    if (!gpioArray || gpioArray.length < 2) {
      const defaults = DEFAULT_GPIO[ctrl.type];
      if (defaults && defaults.length >= 2) {
        gpioArray = [...defaults];
      } else {
        return; // Skip if no multi-pin config
      }
    }

    // For virtual pins, we still setup LEDC channels (the macro exists from generateGPIOConfig)
    // Just comment that it's virtual
    const pinMode = isVirtual ? '// Virtual Pin' : '';

    if (ctrl.type === 'joystick_full' || ctrl.type === 'joystick_x') {
      if (orientation === 'both' || orientation === 'horizontal') {
        setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} X axis ${pinMode} (id=${ctrl.id})\n`;
        setup += `  ledcAttachPin(${uniqueName}_X, ${channel});\n`;
        channel++;
      }
    }

    if (ctrl.type === 'joystick_full' || ctrl.type === 'joystick_y') {
      if (orientation === 'both' || orientation === 'vertical') {
        setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} Y axis ${pinMode} (id=${ctrl.id})\n`;
        setup += `  ledcAttachPin(${uniqueName}_Y, ${channel});\n`;
        channel++;
      }
    }

    if (ctrl.type === 'color_picker') {
      setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} Red ${pinMode} (id=${ctrl.id})\n`;
      setup += `  ledcAttachPin(${uniqueName}_R, ${channel});\n`;
      channel++;

      setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} Green ${pinMode} (id=${ctrl.id})\n`;
      setup += `  ledcAttachPin(${uniqueName}_G, ${channel});\n`;
      channel++;

      setup += `  ledcSetup(${channel}, 1000, 8);  // ${ctrl.label || ctrl.type} Blue ${pinMode} (id=${ctrl.id})\n`;
      setup += `  ledcAttachPin(${uniqueName}_B, ${channel});\n`;
      channel++;
    }

    if (ctrl.type === 'dpad') {
      const pinLabels = ['UP', 'DOWN', 'LEFT', 'RIGHT'];
      gpioArray.forEach((p, idx) => {
        setup += `  pinMode(${uniqueName}_${pinLabels[idx]}, OUTPUT);  // ${ctrl.label || ctrl.type} ${pinLabels[idx]} (id=${ctrl.id})\n`;
      });
    }

    if (ctrl.type === 'stepper') {
      setup += `  pinMode(${uniqueName}_IN1, OUTPUT);  // ${ctrl.label || ctrl.type} IN1 (id=${ctrl.id})\n`;
      setup += `  pinMode(${uniqueName}_IN2, OUTPUT);  // ${ctrl.label || ctrl.type} IN2 (id=${ctrl.id})\n`;
    }
  });

  return setup;
}

function generateLoopCode(controls) {
  // Most operations are handled via HTTP routes, loop is minimal
  return '  // Main loop - HTTP handled in server.handleClient()\n';
}

/**
 * Generate ESP8266 code
 * Key differences from ESP32:
 * - Uses AP mode (creates its own WiFi network)
 * - analogWrite() for PWM instead of ledcWrite()
 * - yield() in loop to prevent watchdog reset
 * - ESP8266WebServer instead of WebServer
 * - Fixed IP: 192.168.4.1/24 subnet
 */
export function generateStandaloneESP8266(controls, htmlContent, options = {}) {
  const {
    ssid = 'ESP_Control',
    password = '12345678',
    serverPort = 80,
    serverEndpoint = 'control',
    apLocalIp = '192.168.4.1',
    apGateway = '192.168.4.1',
    apSubnet = '255.255.255.0',
  } = options;

  const gpioConfig = generateESP8266GPIOConfig(controls);
  const vpMapping = generateVPPinMapping(controls);
  const routes = generateESP8266Routes(controls);
  const setupCode = generateESP8266SetupCode(controls);
  const loopCode = generateESP8266LoopCode(controls);

  // Parse IP addresses for Arduino
  const localIpParts = apLocalIp.split('.').map(Number);
  const gatewayParts = apGateway.split('.').map(Number);
  const subnetParts = apSubnet.split('.').map(Number);

  return `// Auto-generated ESP8266 Standalone Controller
// Generated by IoT Platform
// Date: ${new Date().toISOString()}
// Board: ESP8266 (AP Mode)

// ==================== IP CONFIG (AP Mode) ====================
IPAddress localIP(${localIpParts.join(', ')});
IPAddress gateway(${gatewayParts.join(', ')});
IPAddress subnet(${subnetParts.join(', ')});

// ==================== WIFI AP CONFIG ====================
const char* AP_SSID = "${ssid}";
const char* AP_PASSWORD = "${password}";

// ==================== WEB SERVER ====================
const char* SERVER_ENDPOINT = "${serverEndpoint}";
ESP8266WebServer server(${serverPort});

// ==================== PHYSICAL GPIO PINS ====================
${gpioConfig}

// ==================== VIRTUAL PINS (Blynk) ====================
${vpMapping}

// ==================== CONTROL STATES ====================
${generateESP8266StateVariables(controls)}

// ==================== HTML CONTENT ====================
const char INDEX_HTML[] PROGMEM = R"rawliteral(
${htmlContent}
)rawliteral";

// ==================== WIFI AP START ====================
bool startAP() {
  Serial.println();
  Serial.println("=================================");
  Serial.println("ESP8266 Standalone Controller");
  Serial.print("AP SSID: ");
  Serial.println(AP_SSID);
  Serial.print("AP Password: ");
  Serial.println(AP_PASSWORD);
  Serial.println("=================================");

  WiFi.persistent(false);
  WiFi.disconnect();
  delay(100);

  // Configure static IP before starting AP
  if (!WiFi.softAPConfig(localIP, gateway, subnet)) {
    Serial.println("AP Config Failed!");
  }

  // Start Access Point
  bool success = WiFi.softAP(AP_SSID, AP_PASSWORD);

  if (!success) {
    Serial.println("Failed to start WiFi Access Point!");
    return false;
  }

  Serial.println();
  Serial.println("WiFi Access Point started!");
  Serial.print("AP IP Address: ");
  Serial.println(WiFi.softAPIP());
  Serial.print("Max clients: 4");
  Serial.println();

  return true;
}

// ==================== WEB SERVER SETUP ====================
void setupWebServer() {
  server.on("/", HTTP_GET, handleRoot);
  server.on("/", HTTP_OPTIONS, []() {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(204);
  });
  server.on("/"+String(SERVER_ENDPOINT), HTTP_GET, handleRoot);
  server.on("/"+String(SERVER_ENDPOINT), HTTP_OPTIONS, []() {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(204);
  });

${generateESP8266RouteRegistrations(controls)}

  server.onNotFound([]() {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(404, "application/json", "{\\"success\\":false,\\"message\\":\\"Endpoint not found\\"}");
  });

  server.begin();
  Serial.println("Web Server Started on port 80");
}

// ==================== ROUTES ====================
${routes}

// ==================== SETUP ====================
void setup() {
  Serial.begin(115200);
  delay(1000);

  Serial.println();
  Serial.println("=================================");
  Serial.println("ESP8266 Standalone Controller - AP Mode");
  Serial.print("AP SSID: ");
  Serial.println(AP_SSID);
  Serial.print("AP Password: ");
  Serial.println(AP_PASSWORD);
  Serial.println("=================================");

  // Setup GPIO pins
  ${setupCode}

  // Start AP
  if (!startAP()) {
    Serial.println("Critical Error: Cannot start AP!");
    while (1) {
      delay(1000);
    }
  }

  // Start Web Server immediately
  setupWebServer();
}

// ==================== LOOP ====================
void loop() {
  // Always handle web client - AP mode is always connected
  server.handleClient();
  yield();  // Prevent ESP8266 watchdog reset
${loopCode}
}
`;
}

function generateESP8266GPIOConfig(controls) {
  let config = '// GPIO Pin Definitions\n';

  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_x')) {
    config += '#define PIN_JOYSTICK_X  13  // Joystick X axis\n';
  }
  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_y')) {
    config += '#define PIN_JOYSTICK_Y  15  // Joystick Y axis — NOTE: GPIO15 has internal pull-down, PWM duty may shift slightly\n';
  }
  if (controls.some(c => c.type === 'color_picker')) {
    // ESP8266: use GPIO 12, 13, 14 (safe PWM pins)
    config += '#define PIN_RGB_R       12  // RGB LED Red\n';
    config += '#define PIN_RGB_G       13  // RGB LED Green\n';
    config += '#define PIN_RGB_B       14  // RGB LED Blue\n';
  }
  if (controls.some(c => c.type === 'dpad')) {
    config += '#define PIN_DPAD_UP     16  // D-pad Up\n';
    config += '#define PIN_DPAD_DOWN   5   // D-pad Down\n';
    config += '#define PIN_DPAD_LEFT   4   // D-pad Left\n';
    config += '#define PIN_DPAD_RIGHT  0   // D-pad Right\n';
  }
  if (controls.some(c => ['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(c.type))) {
    config += '#define PIN_RELAY       5   // Relay / LED output\n';
  }
  if (controls.some(c => ['slider', 'knob', 'number_input'].includes(c.type))) {
    // ESP8266 PWM pins
    config += '#define PIN_PWM         4   // PWM output\n';
  }
  if (controls.some(c => c.type === 'stepper')) {
    config += '#define PIN_STEPPER_IN1  12  // Stepper motor IN1\n';
    config += '#define PIN_STEPPER_IN2  14  // Stepper motor IN2\n';
  }

  return config || '// No GPIO pins configured\n';
}

function generateESP8266StateVariables(controls) {
  let states = '// Control States\n';

  if (controls.some(c => ['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(c.type))) {
    states += 'bool relayState = false;\n';
  }

  if (controls.some(c => ['slider', 'knob', 'number_input'].includes(c.type))) {
    states += 'int pwmValue = 0;\n';
  }

  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_x')) {
    states += 'int joystickX = 128; // Center on 0-255 range to match analogWrite midpoint\n';
  }

  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_y')) {
    states += 'int joystickY = 128;\n';
  }

  if (controls.some(c => c.type === 'color_picker')) {
    states += 'int rgbR = 0, rgbG = 0, rgbB = 0;\n';
  }

  if (controls.some(c => c.type === 'stepper')) {
    states += 'int stepperPos = 0;\n';
  }

  return states || '// No states needed\n';
}

function generateESP8266RouteRegistrations(controls) {
  let regs = '';
  const usedHandlers = new Set();

  // Register per-widget routes with unique endpoints based on widget id
  controls.forEach((ctrl) => {
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const widgetId = sanitizeWidgetId(ctrl.id);
    const handlerName = `handle${gpioName}_${widgetId}`;
    // Skip if handler already registered (shouldn't happen with unique ids)
    if (usedHandlers.has(handlerName)) return;
    usedHandlers.add(handlerName);

    // Unique endpoint per widget - MUST match HTML generator's widgetEndpoint()
    const endpoint = widgetEndpoint(ctrl);

    // Dispatch to type-specific handler logic via unique wrapper function
    if (['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(ctrl.type)) {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'slider' || ctrl.type === 'knob' || ctrl.type === 'number_input') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'joystick_full') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'joystick_x' || ctrl.type === 'joystick_y') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'color_picker') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'dpad') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    } else if (ctrl.type === 'stepper') {
      regs += `  server.on("${endpoint}", HTTP_GET, ${handlerName});\n`;
    }
  });

  return regs || '  // No routes registered\n';
}

function generateESP8266Routes(controls) {
  let routes = `// ==================== HANDLE ROOT ====================
void handleRoot() {
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send_P(200, "text/html", INDEX_HTML);
}

`;

  // Generate per-widget handlers with unique names + unique endpoints
  controls.forEach((ctrl) => {
    const gpioName = sanitizeCIdentifier(ctrl.gpioName || ctrl.type).toUpperCase();
    const widgetId = sanitizeWidgetId(ctrl.id);
    const handlerName = `handle${gpioName}_${widgetId}`;
    const endpoint = widgetEndpoint(ctrl);
    // Escape label for C string literal (escape backslash and double-quote)
    const label = String(ctrl.label || ctrl.type).replace(/\\/g, '\\\\').replace(/"/g, '\\"');

    // Shared CORS header + send helper invoked at the end of every handler.
    const sendCors = (code, body) =>
      `  server.sendHeader("Access-Control-Allow-Origin", "*");\n  server.send(${code}, "text/plain", ${body});\n`;

    if (['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(ctrl.type)) {
      routes += `// ==================== HANDLE OUTPUT (button/toggle/checkbox/icon_button/touch_pad) ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("state")) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing state arg");
    return;
  }

  String stateArg = server.arg("state");
  if (stateArg.length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Empty state arg");
    return;
  }

  int stateVal = stateArg.toInt();
  relayState = (stateVal == 1);
  digitalWrite(PIN_RELAY, relayState ? HIGH : LOW);
  Serial.print("${label}: ");
  Serial.println(relayState ? "ON" : "OFF");
${sendCors(200, 'relayState ? "ON" : "OFF"')}
}

`;
    }

    if (ctrl.type === 'slider' || ctrl.type === 'knob' || ctrl.type === 'number_input') {
      routes += `// ==================== HANDLE ${ctrl.type.toUpperCase()} ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("value")) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing value arg");
    return;
  }

  String valArg = server.arg("value");
  if (valArg.length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Empty value arg");
    return;
  }

  pwmValue = valArg.toInt();
  pwmValue = constrain(pwmValue, 0, 255);
  analogWrite(PIN_PWM, pwmValue);
  Serial.print("${label}: ");
  Serial.println(pwmValue);
${sendCors(200, 'String(pwmValue)')}
}

`;
    }

    if (ctrl.type === 'joystick_full') {
      routes += `// ==================== HANDLE JOYSTICK ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (server.hasArg("x") && server.arg("x").length() > 0) {
    joystickX = server.arg("x").toInt();
    joystickX = constrain(joystickX, 0, 255);
    analogWrite(PIN_JOYSTICK_X, joystickX);
    Serial.print("${label} X: ");
    Serial.println(joystickX);
  }

  if (server.hasArg("y") && server.arg("y").length() > 0) {
    joystickY = server.arg("y").toInt();
    joystickY = constrain(joystickY, 0, 255);
    analogWrite(PIN_JOYSTICK_Y, joystickY);
    Serial.print("${label} Y: ");
    Serial.println(joystickY);
  }

  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(200, "text/plain", "OK");
}

`;
    }

    if (ctrl.type === 'joystick_x') {
      routes += `// ==================== HANDLE JOYSTICK X ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("value") || server.arg("value").length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing value arg");
    return;
  }

  joystickX = server.arg("value").toInt();
  joystickX = constrain(joystickX, 0, 255);
  analogWrite(PIN_JOYSTICK_X, joystickX);
  Serial.print("${label} X: ");
  Serial.println(joystickX);
${sendCors(200, 'String(joystickX)')}
}

`;
    }

    if (ctrl.type === 'joystick_y') {
      routes += `// ==================== HANDLE JOYSTICK Y ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("value") || server.arg("value").length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing value arg");
    return;
  }

  joystickY = server.arg("value").toInt();
  joystickY = constrain(joystickY, 0, 255);
  analogWrite(PIN_JOYSTICK_Y, joystickY);
  Serial.print("${label} Y: ");
  Serial.println(joystickY);
${sendCors(200, 'String(joystickY)')}
}

`;
    }

    if (ctrl.type === 'color_picker') {
      routes += `// ==================== HANDLE RGB ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (server.hasArg("r") && server.arg("r").length() > 0) rgbR = server.arg("r").toInt();
  if (server.hasArg("g") && server.arg("g").length() > 0) rgbG = server.arg("g").toInt();
  if (server.hasArg("b") && server.arg("b").length() > 0) rgbB = server.arg("b").toInt();

  rgbR = constrain(rgbR, 0, 255);
  rgbG = constrain(rgbG, 0, 255);
  rgbB = constrain(rgbB, 0, 255);

  analogWrite(PIN_RGB_R, rgbR);
  analogWrite(PIN_RGB_G, rgbG);
  analogWrite(PIN_RGB_B, rgbB);

  Serial.print("${label} RGB: R=");
  Serial.print(rgbR);
  Serial.print(" G=");
  Serial.print(rgbG);
  Serial.print(" B=");
  Serial.println(rgbB);
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(200, "text/plain", "OK");
}

`;
    }

    if (ctrl.type === 'dpad') {
      routes += `// ==================== HANDLE D-PAD ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("dir") || server.arg("dir").length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing dir arg");
    return;
  }

  String dir = server.arg("dir");
  dir.toUpperCase();
  Serial.print("${label}: ");
  Serial.println(dir);

  // Reset all D-pad pins
  digitalWrite(PIN_DPAD_UP, LOW);
  digitalWrite(PIN_DPAD_DOWN, LOW);
  digitalWrite(PIN_DPAD_LEFT, LOW);
  digitalWrite(PIN_DPAD_RIGHT, LOW);

  if (dir == "UP") digitalWrite(PIN_DPAD_UP, HIGH);
  else if (dir == "DOWN") digitalWrite(PIN_DPAD_DOWN, HIGH);
  else if (dir == "LEFT") digitalWrite(PIN_DPAD_LEFT, HIGH);
  else if (dir == "RIGHT") digitalWrite(PIN_DPAD_RIGHT, HIGH);

  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(200, "text/plain", "OK");
}

`;
    }

    if (ctrl.type === 'stepper') {
      routes += `// ==================== HANDLE STEPPER ====================
// Widget: ${label} (id=${ctrl.id})
void ${handlerName}() {
  if (!server.hasArg("dir") || server.arg("dir").length() == 0) {
    server.sendHeader("Access-Control-Allow-Origin", "*");
    server.send(400, "text/plain", "Missing dir arg");
    return;
  }

  String dir = server.arg("dir");
  dir.toLowerCase();
  Serial.print("${label}: ");
  Serial.println(dir);

  if (dir == "up") {
    digitalWrite(PIN_STEPPER_IN1, HIGH);
    digitalWrite(PIN_STEPPER_IN2, LOW);
    delay(10);
    digitalWrite(PIN_STEPPER_IN1, LOW);
    digitalWrite(PIN_STEPPER_IN2, HIGH);
    delay(10);
    stepperPos++;
  } else if (dir == "down") {
    digitalWrite(PIN_STEPPER_IN1, LOW);
    digitalWrite(PIN_STEPPER_IN2, HIGH);
    delay(10);
    digitalWrite(PIN_STEPPER_IN1, HIGH);
    digitalWrite(PIN_STEPPER_IN2, LOW);
    delay(10);
    stepperPos--;
  }

  Serial.print("Position: ");
  Serial.println(stepperPos);
  server.sendHeader("Access-Control-Allow-Origin", "*");
  server.send(200, "text/plain", String(stepperPos));
}

`;
    }
  });

  return routes || '// No custom routes\n';
}

function generateESP8266SetupCode(controls) {
  let setup = '  // Configure GPIO pins\n';

  // ESP8266 PWM range: default is 0-1023, set to 0-255 so generator's
  // constrain(value, 0, 255) actually reaches 100% duty cycle.
  if (controls.some(c => ['slider', 'knob', 'number_input', 'joystick_full', 'joystick_x', 'joystick_y', 'color_picker'].includes(c.type))) {
    setup += '  analogWriteRange(255);\n';
    setup += '  analogWriteFreq(1000); // 1kHz PWM\n';
  }

  if (controls.some(c => ['button', 'toggle', 'checkbox', 'icon_button', 'touch_pad'].includes(c.type))) {
    setup += '  pinMode(PIN_RELAY, OUTPUT);\n';
    setup += '  digitalWrite(PIN_RELAY, LOW);\n';
  }

  if (controls.some(c => c.type === 'dpad')) {
    setup += '  pinMode(PIN_DPAD_UP, OUTPUT);\n';
    setup += '  pinMode(PIN_DPAD_DOWN, OUTPUT);\n';
    setup += '  pinMode(PIN_DPAD_LEFT, OUTPUT);\n';
    setup += '  pinMode(PIN_DPAD_RIGHT, OUTPUT);\n';
    setup += '  digitalWrite(PIN_DPAD_UP, LOW);\n';
    setup += '  digitalWrite(PIN_DPAD_DOWN, LOW);\n';
    setup += '  digitalWrite(PIN_DPAD_LEFT, LOW);\n';
    setup += '  digitalWrite(PIN_DPAD_RIGHT, LOW);\n';
  }

  if (controls.some(c => ['slider', 'knob', 'number_input', 'joystick_full', 'joystick_x', 'joystick_y', 'color_picker'].includes(c.type))) {
    setup += '\n  // Initialize PWM pins (ESP8266 uses analogWrite)\n';

    if (controls.some(c => ['slider', 'knob', 'number_input'].includes(c.type))) {
      setup += '  pinMode(PIN_PWM, OUTPUT);\n';
    }

    if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_x')) {
      setup += '  pinMode(PIN_JOYSTICK_X, OUTPUT);\n';
    }

    if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_y')) {
      setup += '  pinMode(PIN_JOYSTICK_Y, OUTPUT);\n';
    }

    if (controls.some(c => c.type === 'color_picker')) {
      setup += '  pinMode(PIN_RGB_R, OUTPUT);\n';
      setup += '  pinMode(PIN_RGB_G, OUTPUT);\n';
      setup += '  pinMode(PIN_RGB_B, OUTPUT);\n';
    }
  }

  if (controls.some(c => c.type === 'stepper')) {
    setup += '  pinMode(PIN_STEPPER_IN1, OUTPUT);\n';
    setup += '  pinMode(PIN_STEPPER_IN2, OUTPUT);\n';
  }

  // Initialize PWM outputs to match state variables so pins are not floating
  // at boot. Without this, LED/motor may flicker for 1-2s before the first
  // request from the UI lands.
  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_x')) {
    setup += '\n  // Initialize joystick PWM to center (128) on first boot\n';
    setup += '  analogWrite(PIN_JOYSTICK_X, joystickX);\n';
  }

  if (controls.some(c => c.type === 'joystick_full' || c.type === 'joystick_y')) {
    setup += '  analogWrite(PIN_JOYSTICK_Y, joystickY);\n';
  }

  if (controls.some(c => ['slider', 'knob', 'number_input'].includes(c.type))) {
    setup += '\n  // Initialize PWM to 0 on first boot\n';
    setup += '  analogWrite(PIN_PWM, pwmValue);\n';
  }

  if (controls.some(c => c.type === 'color_picker')) {
    setup += '\n  // Initialize RGB PWM to 0 on first boot\n';
    setup += '  analogWrite(PIN_RGB_R, rgbR);\n';
    setup += '  analogWrite(PIN_RGB_G, rgbG);\n';
    setup += '  analogWrite(PIN_RGB_B, rgbB);\n';
  }

  return setup;
}

function generateESP8266LoopCode(controls) {
  let loop = '    // Main loop - HTTP handled in server.handleClient()\n';

  // Periodic tasks could be added here

  return loop;
}
